"""Formal split of the Sachs path integral (paper Fig.~\\ref{fig:cumulant-hierarchy}).

A compact, line-art "building-blocks" map in the paper's muted schematic palette.
It introduces, with the SAME glyphs used by the Feynman figures that follow
(Figs.~3-4), the four objects of the perturbative expansion:

  free theory S_0       interaction S_int
    R  response  (red dashed arrow)   F        local vertex   (black square)
    C  correlation (blue solid line)  K^(n)    source cumulant (black square)

No tinted boxes/blocks: symbols and glyphs are typeset directly.

Output:
    figures/cumulant_hierarchy.{pdf,png}
"""
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch

ROOT = Path(__file__).resolve().parents[2]
FIGURES = ROOT / "figures"

# ----- muted schematic palette (cf. make_screen_basis_spin2_figure.py) -----
INK = "#16202a"
BLUE = "#2f6f9f"      # C, correlation propagator
CORAL = "#b95f58"     # R, response propagator
GRAY = "#68717d"      # descriptors / hairlines
HAIR = "#c8cdd4"      # faint rules


def setup_style() -> None:
    plt.rcParams.update({
        "figure.dpi": 150,
        "savefig.dpi": 360,
        "font.family": "serif",
        "font.serif": ["CMU Serif", "Computer Modern Roman", "DejaVu Serif"],
        "mathtext.fontset": "cm",
        "font.size": 9.0,
        "axes.linewidth": 0.0,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    })


def _resp_glyph(ax, x0, x1, y):
    """R: short red/coral dashed arrow (the response-propagator glyph)."""
    ax.add_patch(FancyArrowPatch(
        (x0, y), (x1, y), arrowstyle="-|>", mutation_scale=8,
        color=CORAL, lw=1.4, ls=(0, (4, 2)), shrinkA=0, shrinkB=0, zorder=4))


def _corr_glyph(ax, x0, x1, y):
    """C: short blue solid line (the correlation-propagator glyph)."""
    ax.plot([x0, x1], [y, y], color=BLUE, lw=1.7, solid_capstyle="round",
            zorder=4)


def _vertex(ax, x, y):
    """F / K^(n): filled black square (the interaction-vertex glyph)."""
    ax.plot([x], [y], marker="s", color=INK, markersize=7.5, zorder=5)


def render(seed: int, out_stem: Path) -> None:
    del seed
    setup_style()
    fig, ax = plt.subplots(figsize=(8.6, 2.7))
    ax.set_xlim(0, 14)
    ax.set_ylim(0, 5)
    ax.axis("off")

    # ----- master equation (no box) + faint rule under it -----
    ax.text(7.0, 4.62,
            r"$\dot{\mathcal{X}}_a - A_{ab}\mathcal{X}_b "
            r"= F_{abc}\mathcal{X}_b\mathcal{X}_c + \varphi_a,"
            r"\qquad \langle\varphi_a\rangle = 0$",
            color=INK, fontsize=10.5, ha="center", va="center")
    ax.plot([0.4, 13.6], [4.08, 4.08], color=HAIR, lw=0.8, zorder=1)
    # vertical divider between the two groups
    ax.plot([7.0, 7.0], [0.35, 3.75], color=HAIR, lw=0.8, zorder=1)

    # ----- group headers -----
    ax.text(3.05, 3.5, r"free theory  $S_0$", color=BLUE, fontsize=10.0,
            ha="center", va="center")
    ax.text(10.5, 3.5, r"interaction  $S_{\rm int}$", color=CORAL,
            fontsize=10.0, ha="center", va="center")

    yR, yC = 2.35, 0.95          # row baselines

    # ----- left group: free propagators -----
    _resp_glyph(ax, 0.7, 1.75, yR)
    ax.text(2.05, yR, r"$\mathcal{R}$", color=INK, fontsize=12, ha="left", va="center")
    ax.text(2.7, yR + 0.02, "response propagator", color=INK, fontsize=8.6,
            ha="left", va="center")
    ax.text(2.7, yR - 0.55, r"generated by $A_{ab}$", color=GRAY, fontsize=7.6,
            ha="left", va="center", style="italic")

    _corr_glyph(ax, 0.7, 1.75, yC)
    ax.text(2.05, yC, r"$\mathcal{C}$", color=INK, fontsize=12, ha="left", va="center")
    ax.text(2.7, yC + 0.02, "correlation propagator", color=INK, fontsize=8.6,
            ha="left", va="center")
    ax.text(2.7, yC - 0.55, r"generated by $\mathcal{K}^{(2)}=\langle\varphi\varphi\rangle_c$",
            color=GRAY, fontsize=7.6, ha="left", va="center", style="italic")

    # ----- right group: interaction vertices -----
    _vertex(ax, 7.75, yR)
    ax.text(8.1, yR, r"$F$", color=INK, fontsize=12, ha="left", va="center")
    ax.text(8.6, yR + 0.02, "nonlinear-propagation vertex", color=INK,
            fontsize=8.6, ha="left", va="center")
    ax.text(8.6, yR - 0.55, r"$F_{abc}\mathcal{X}_b\mathcal{X}_c$", color=GRAY,
            fontsize=7.6, ha="left", va="center", style="italic")

    _vertex(ax, 7.75, yC)
    ax.text(8.1, yC, r"$\mathcal{K}^{(n)}$", color=INK, fontsize=12, ha="left",
            va="center")
    ax.text(8.95, yC + 0.02, "source cumulants", color=INK, fontsize=8.6,
            ha="left", va="center")
    ax.text(8.95, yC - 0.55,
            r"$\langle\varphi\cdots\varphi\rangle_c,\ n\geq3$", color=GRAY,
            fontsize=7.6, ha="left", va="center", style="italic")

    pdf = out_stem.with_suffix(".pdf")
    png = out_stem.with_suffix(".png")
    FIGURES.mkdir(parents=True, exist_ok=True)
    fig.savefig(pdf, bbox_inches="tight", pad_inches=0.04, facecolor="white")
    fig.savefig(png, dpi=300, bbox_inches="tight", pad_inches=0.04, facecolor="white")
    plt.close(fig)
    print(f"wrote {pdf}")
    print(f"wrote {png}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--out-stem", type=Path,
                        default=FIGURES / "cumulant_hierarchy")
    args = parser.parse_args()
    render(args.seed, args.out_stem)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
