system:
  field:
    name: phi
    n_components: 3
  linear:
    type: explicit
    R_time_module: /Users/zzhang/Documents/MyDrafts/STF_lensing/SFT-lensing-paper-analyses/sachs_sft/scripts/D_callable.py
    R_time_attr: response_R
    iso_R: true
  noise:
    kappa2:
      type: callable_module
      module: /Users/zzhang/Documents/MyDrafts/STF_lensing/SFT-lensing-paper-analyses/sachs_sft/scripts/kappa2_callable.py
      attr: kappa2
  vertices:
  - name: F
    coupling_path: /Users/zzhang/Documents/MyDrafts/STF_lensing/SFT-lensing-paper-analyses/sachs_sft/scripts/inputs/F_tensor.npy
expand:
  observable:
  - "phi_a(x)"
  - "phi_b(y)"
  orders:
  - 0
  response_phase: true
  ito: true
  collect_topology: true
  diag_R: true
  diag_C: false
  cache_path: /Users/zzhang/Documents/MyDrafts/STF_lensing/driver_field_emulators/code/mc_fk_complete/psd_fix/fold_bias/rec_O0/.cache_expand_C_corr_op_O0
  n_jobs: 1
propagators:
  t_max: 2360.0
  dt: 1.0
  homogeneity: rotation
  n_grid_cos: 32
  n_jobs: 1
  cache_path: /Users/zzhang/Documents/MyDrafts/STF_lensing/driver_field_emulators/code/mc_fk_complete/psd_fix/fold_bias/rec_O0/.cache_propagators_C_corr_op_O0
  c_closed_form_module: /Users/zzhang/Documents/MyDrafts/STF_lensing/driver_field_emulators/code/mc_fk_complete/psd_fix/fold_bias/recording_C_callable.py
  c_closed_form_attr: C_fn
  c_closed_form_only: true
  c_closed_form_vectorized: false
  c_method: gauss_legendre
  c_n_gauss: 20
  diag_C: false


sweep:
  integrate_over: "all"

  # 40 log-spaced gamma points from 0.5 to 5000 arcmin
  positions_grid:
    x:
      - [0.0, 0.0, 1.0]
    y:
      - [0.0001454441, 0.0, 0.9999999894]    # gamma = 0.5000 arcmin
      - [0.0050252287, 0.0, 0.9999873735]    # gamma = 17.2755 arcmin
      - [0.0853881735, 0.0, 0.9963477605]    # gamma = 293.9008 arcmin

  t_final_grid:
  - 2313.0288751857356
  
  component_pairs:
    - [0, 0]   # kappa-kappa
    - [0, 1]   # kappa-gamma_+
    - [0, 2]   # kappa-gamma_x
    - [1, 1]   # gamma_+-gamma_+
    - [1, 2]   # gamma_+-gamma_x
    - [2, 2]   # gamma_x-gamma_x

  method: gauss_legendre
  n_gauss: 24
  n_jobs: 1
output:
- type: npz
  path: /Users/zzhang/Documents/MyDrafts/STF_lensing/driver_field_emulators/code/mc_fk_complete/psd_fix/fold_bias/rec_O0/xi_C_corr_op_O0.npz
